app:
  stage: "prod"
  discord:
    token: ${DISCORD_TOKEN}
    application-id: ${DISCORD_APPLICATION_ID}
  sentry:
    dsn: ${SENTRY_DSN}
  ftw:
    url: ${FTW_URL}
    key: ${FTW_KEY}

logging:
  level:
    root: INFO
  file:
    name: "bot.log"